config/routes.rb
Rails.application.routes.draw do
  devise_for :administradors, controllers: {sessions: 'administradors/sessions' }
  devise_for :users, controllers: {sessions: 'users/sessions' }
   
  get 'order_details/new'

  get 'order_details/show'

  get 'order_details/destroy'

  get 'payment/send'

  get 'payment/receive'

       resources :posts do

       resources :comments
end

  root 'posts#index'

    get '/cristina' => 'posts#new'
    get '/rios',to:'posts#index'

end

app/models/post.rb
class Post < ActiveRecord::Base
	

	has_many :comments, dependent: :destroy
	validates_presence_of :title, :message=>"El campo esta vacio"
      validates_length_of :body, :in=> 10..400,:message=>"longitud no valida"
      belongs_to :user


end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    if user_signed_in?
        @posts = current_user.posts
      else
        @posts = Post.all
  end
  

end
  # GET /posts/1
  # GET /posts/1.json
  def show
     @posts = Post.all
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user_id=current_user.id
    respond_to do |format|
      if @post.save
        flash[:success] = "se guardo correctamente el posts"
        format.html { redirect_to @post}
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        flash[:warining] = "No se guardo el posts"
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        flash[:success] = "se Actualizo correctamente el posts"
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        flash[:warining] = "No se Actualizo el posts"
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      flash[:success] = "se elimino correctamente el posts"
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title, :class=> "validate[required]" %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body , :class=> "validate[required]"%>
  </div>


  <section class="row">
  <div class="small-4 columns">
    <div class="actions">
      <%= f.submit 'Aceptar', :class => 'button smal success radius' %>
    </div>
   </div>
</section>

<% end %>

app/views/posts/_navigation.html.erb

<nav class="top-bar" data-topbar role="navigation">
	<ul class="title-area">
		<li class="name">
			<h1><a href="#">Post</a></h1>
		</li>
	</ul>
	<section class="top-bar-section">
		<ul class="left">
			<li class="has-dropdown not-click"><a href="#">Menu</a>
				<ul class="dropdown">
					<li class="title back js-generated" href="#">
						<h5>
							<a href="javascript:void(0)">Back</a>
						</h5>
					</li>
					<li class="parent-link show-for-small-only">
						<a class="parent-link js-generated" href="#">Inicio</a>
					</li>
					<li>
						<label>Menu</label>
					</li>
					<% if user_signed_in? %>
					<li><%= link_to'Ver',controller:'/posts',action:'index'%></li>
					<li><%= link_to'Nuevo',controller:'/posts',action:'new'%></li>
					<%end%>
				</ul>
			</li>
			<li class="divider"></li>
		</ul>


<ul class="right">
	<% if user_signed_in? || administrador_signed_in? %>
			<li><a>Logged ini as <strong><%= current_user ? current_user.email : current_administrador.email %></strong>.</a></li>

			<ul class="right">
				

					<li><%=link_to 'Edit Profile', current_user ? edit_user_registration_path : edit_administrador_registration_path, :class=>'navbar-link'%></li>
					<li><%=link_to "Logout", destroy_user_session_path, method: :delete, :class=>'navbar-link'%></li>
				</ul>



			<%else%>

		<ul class="right">
				<li class="has-dropdown not-click"><a href="#">Sing up</a>
					<ul class="dropdown">
						<li>
							<label>Sing up</label>
						</li>
						<li><%= link_to'User', new_user_registration_path,:class=>'navbar-link'%></li>
						<li><%=link_to 'Admin', new_administrador_registration_path,:class=>'navbar-link'%></li>
					</ul>
				</li>

			</ul>
			<ul class="right">
				<li class="has-dropdown not-click"><a href="#">Login</a>
					<ul class="dropdown">
						<li>
							<label>Login</label>
						</li>
						<li><%= link_to'User', new_user_session_path,:class=>'navbar-link'%></li>
						<li><%=link_to 'Admin', new_administrador_session_path,:class=>'navbar-link'%></li>
					</ul>
				</li>

			</ul>
			<%end%>
</ul>

	</section>

</nav>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Listing posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <% if administrador_signed_in? %>
      <th>E-mail</th>
      <%end%>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td>
          <% if post.body %> 
          <a href="#"data-reveal-id="post-<%=post.id%>">Ver post</a>
          <div id="post-<%=post.id%>"class="reveal-modal" data-reveal>
              <%=post.body %>
              <a class="close-reveal-modal">&#215;</a>
           </div>
           <% end %>
        </td>
        <% if administrador_signed_in? %>
         <td><%=User.find(post.user_id).email%></td>
        <%end%>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if user_signed_in? %>
<%= link_to 'New Post', new_post_path, :class => 'links' %>

<%end%>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>


<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<!-- <p id="notice"><%= notice %></p> -->

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @post.body %>
</p>

<div id="comments">
	<%= render :partial => @post.comments.reverse %>
 </div>

<%= form_for([@post, Comment.new], remote: true) do |f| %>
	<p> <%= f.label :body,"New Comment"%> <br/>
	<%= f.text_area :body %>
</p>


	 <section class="row">
  <div class="small-4 columns">
    <div class="actions">
      <%= f.submit 'Aceptar', :class => 'button smal success radius' %>
    </div>
   </div>
</section>
  
<% end %>


<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>}